### PR TITLE
v1.0.0.0

### PR DESCRIPTION
**Pull request by matthewtiscareno**
v1.0.0.0

## Summary

Updated definitions for a large fraction of the attributes, resolving various questions and preparing for release.

## Test Data and/or Report

Enter info here

## Related Issues

Enter related issues here

### CODE REVIEW

**Review by katecrombie — CHANGES_REQUESTED** [review]
It looks like there was one error when running the ldd tool.  It is noted in logs/v1.16.0.0_execution_logs/validate_report_20240327052136.txt.  

Error on line 395 column 67 of PDS4_VGR_1G00_1000.xsd:
  SXXP0003   Error reported by XML parser: The element type "xs:documentation" must be
  terminated by the matching end-tag "</xs:documentation>".: 

Once that is corrected, this will be ready to go.  Nice job on the LDD definitions update.

**Comment by matthewtiscareno** [comment]
Thanks, Kate.  I have no idea why that error occurred.  The string `xs:documentation` does not occur in the IngestLDD file.  

I appreciate the positive review.  @rgdeen and I spent over an hour yesterday going through outstanding issues, and it was very productive.

**Review by katecrombie — APPROVED** [review]

**Comment by matthewtiscareno** [comment]
Ah, I just needed to update `pds4_versions.txt`.  Tests pass now.

**Review by katecrombie — APPROVED** [review]

**Comment by katecrombie** [comment]
I approved the update that removed the error.  Thanks for figuring that one out.

**Comment by matthewtiscareno** [comment]
This is really strange.  I could have sworn that I saw the tests pass 6hr ago, which would be why Kate was able to approve the PR.  

However, not only are the tests now failing again (for the same reason as before) after my new minor update, but it is saying that the tests also failed 6hr ago. 

@jordanpadams: Any insight?

**Comment by jordanpadams** [comment]
@matthewtiscareno super weird. I will need to poke at this some more.

**Comment by jordanpadams** [comment]
This is an LDDTool bug...

**Comment by matthewtiscareno** [comment]
@jordanpadams: It seems to work again.  I don't know whether you did anything.

**Comment by matthewtiscareno** [comment]
Wait, no.  In some places it's green and in other places it's red.  I'll step back and let EN handle this.

**Comment by jordanpadams** [comment]
@matthewtiscareno it seems like it is still failing for some reason: https://github.com/pds-data-dictionaries/ldd-vgr/actions/runs/8459517729. I have ticket out to get Steve to take a look.

**Comment by jordanpadams** [comment]
@matthewtiscareno yeah sorry about that. The status checks above that indicate green/red require configuration on a repository by repository basis and it is exhausting to get it out to all repos. Just updated the branch protections to include the LDD generation as a status check in the the future: https://github.com/pds-data-dictionaries/ldd-vgr/settings/branch_protection_rules/25725039

**Comment by matthewtiscareno** [comment]
Thanks for looking into this.  I think I'll add a few schematron rules before I publish this, so the bug is not yet holding up the process. 

Just let me know if you need anything from me.

**Comment by jordanpadams** [comment]
@matthewtiscareno sorry for the issue. @jshughes [identified a workaround](https://github.com/NASA-PDS/pds4-information-model/issues/744#issuecomment-2028465893), so [I updated your IngestLDD with some whitespace](https://github.com/pds-data-dictionaries/ldd-vgr/pull/14/commits/979aa6e0fc71f025b898386090a03c7438fbbeb9), and things looks like they build successfully now.

Be sure to pull the latest code before making any additional updates.

**Comment by matthewtiscareno** [comment]
Thank you, @jordanpadams.  I'll let you know if anything else arises.

**Comment by matthewtiscareno** [comment]
@jordanpadams:  I'm trying to add a unit test to this LDD, my first time doing so.  It is failing with the message `The prefix "vgr" for element "vgr:Voyager" is not bound`, which seems to mean that the schema for this LDD is not being properly invoked.  However, I think I've used the template as it exists [here](https://github.com/pds-data-dictionaries/ldd-template/blob/main/test/test1_VALID.xml).

**Comment by matthewtiscareno** [comment]
@jordanpadams:  I deleted my message from an hour ago, because I figured out that particular problem.  Now it looks like my unit tests are showing that my schematron rules aren't quite right.  I'm not sure whether you or @rsjoyner or someone else at EN can help me troubleshoot the schematron rules.

**Comment by jordanpadams** [comment]
@matthewtiscareno can you link in here which schematron rule you are referring to and the use case you are trying to cover? Then @rsjoyner or I can try to help out.

**Comment by matthewtiscareno** [comment]
The schematron rules are in the `DD_Rule` statements at the end of the `IngestLDD` file in branch `v1.0`
https://github.com/pds-data-dictionaries/ldd-vgr/blob/v1.0/src/PDS4_VGR_IngestLDD.xml

**Comment by jordanpadams** [comment]
@matthewtiscareno We will take a look at the schematron.

On a different topic, I noticed several attributes in the VGR LDD that are also in the IMG and MSN Discipline LDDs. Is there a rationale for not using those attributes instead? Here are a few I saw:

From IMG:
* gain_mode_id - https://pds.nasa.gov/datastandards/documents/dd/all/current/#ch17s112.html
* exposure_duration - https://pds.nasa.gov/datastandards/documents/dd/all/current/#ch17s66.html
* filter_name - https://pds.nasa.gov/datastandards/documents/dd/all/current/#ch17s79.html
* filter_number - https://pds.nasa.gov/datastandards/documents/dd/all/current/#ch17s80.html
* (and I think there could be arguments for adding a lot of the others into the IMG LDD)

* Mission_Information class - https://pds.nasa.gov/datastandards/documents/dd/all/current/#ch22s01.html#N603064758
  * [mission_​phase_​name](https://pds.nasa.gov/datastandards/documents/dd/all/current/ch23s10.html#N-1997020480)
  * [spacecraft_​clock_​start](https://pds.nasa.gov/datastandards/documents/dd/all/current/ch23s15.html#N-548352662)
  * [spacecraft_​clock_​stop](https://pds.nasa.gov/datastandards/documents/dd/all/current/ch23s16.html#N1367784954)
  * [spacecraft_​clock_​partition](https://pds.nasa.gov/datastandards/documents/dd/all/current/ch23s14.html#N432232434)

**Comment by jordanpadams** [comment]
@rsjoyner ☝️

**Comment by matthewtiscareno** [comment]
@jordanpadams: All of these attributes require enumerated lists and/or formats that are mission-specific.  Unless the MSN dictionary were to implement a massive schematron infrastructure to make sure that Voyager data products use only Voyager-appropriate values for these attributes, then I do not think these attributes are well-suited for the MSN dictionary. 

In fact, one of the schematron rules I am trying to implement is just one small example of this.  Because this LDD is for both Voyager 1 and Voyager 2, I want to make sure that certain values of `mission_phase_name` that are only appropriate for Voyager 2 (such as `Uranus Encounter`) are not used for Voyager 1 data products.  To my knowledge, the MSN dictionary has nothing resembling this.

Doing this on a more massive scale seems to be contrary to the principle of having separate LDDs for items that are treated separately and unified LDDs for items that are treated commonly.

I am following the lead of the Cassini LDD, which treats these attributes similiarly to how the Voyager LDD is treating them.

**Comment by matthewtiscareno** [comment]
@jordanpadams:  I see you fixed some syntax in my schematron rules and unit tests (thank you!!!).  The Actions tab says that the tests ran successfully, but the PR below says that "Some checks haven't completed yet."

Is everything fixed?  Should we proceed with publishing this LDD?

**Comment by jordanpadams** [comment]
@matthewtiscareno you should be good to go. Unfortunately, I can't figure out how to get those status checks to turn green...

**Comment by jordanpadams** [comment]
> @jordanpadams: All of these attributes require enumerated lists and/or formats that are mission-specific. Unless the MSN dictionary were to implement a massive schematron infrastructure to make sure that Voyager data products use only Voyager-appropriate values for these attributes, then I do not think these attributes are well-suited for the MSN dictionary.
> 
> In fact, one of the schematron rules I am trying to implement is just one small example of this. Because this LDD is for both Voyager 1 and Voyager 2, I want to make sure that certain values of `mission_phase_name` that are only appropriate for Voyager 2 (such as `Uranus Encounter`) are not used for Voyager 1 data products. To my knowledge, the MSN dictionary has nothing resembling this.
> 
> Doing this on a more massive scale seems to be contrary to the principle of having separate LDDs for items that are treated separately and unified LDDs for items that are treated commonly.
> 
> I am following the lead of the Cassini LDD, which treats these attributes similiarly to how the Voyager LDD is treating them.

@matthewtiscareno Copy that and understood that the schematron would be complex for this.

Short answer: Unfortunately, we did not dedicate enough resources to come up with an easier method to enable slight variations to classes/attributes, so we will need to figure out how to build the layers around the system to support some of these more generic use cases.

Long answer: In general, the point of Discipline LDDs is really intended to support the end user trying to search for or use the data, not really the data provider. You do not need to know specifics about a mission in order to ask our system what phases does a mission have or filters were applied to the data, and then search by that. By duplicating (and potentially renaming) classes and attributes into mission LDDs, it puts the responsibility on the end user to know that _in Voyager metadata that attribute is X while in Cassini it is Y and TBD Future Cool Mission it is Z_, versus _this is an visible image product, so I know all of the attributes I care about_. This will get very onerous on folks trying to develop generic tools that "just work" with PDS4 data. For instance, if you were to develop a generic search tool:

```
if voyager:
  search by X
if cool mission:
  search by Y
if cooler mission:
  search by Z
if coolest mission ever:
  search by A
```

**Comment by matthewtiscareno** [comment]
@jordanpadams:  You know that we at RMS are as zealous as anybody when it comes to cross-mission search.  However, in order to do that sensibly, we carefully consider which attributes are amenable to cross-mission search and which are not.  To my knowledge, no two missions ever have exactly the same filters and filter names, so nobody will ever want to do a cross-mission search on filter names.  On the other hand, people definitely do want to do cross-mission search on the wavelengths that various filters correspond to, which is why we have spent time facilitating such searches on OPUS. 

I think this same principle applies to all the attributes you mention in your message above.

**Comment by matthewtiscareno** [comment]
> @matthewtiscareno you should be good to go. Unfortunately, I can't figure out how to get those status checks to turn green...

Thank you!!!

**Comment by matthewtiscareno** [comment]
@jordanpadams:  You know that we at RMS are as zealous as anybody when it comes to cross-mission search.  However, in order to do that sensibly, we carefully consider which attributes are amenable to cross-mission search and which are not.  

To my knowledge, no two missions ever have exactly the same filters and filter names, so nobody will ever want to do a cross-mission search on filter names.  On the other hand, people definitely do want to do cross-mission search on the wavelengths that various filters correspond to, which is why we have spent time carefully curating the content of wavelength-related attributes in order to facilitate such searches on OPUS. 

I think this same principle applies to all the attributes you mention in your message above.

**Comment by jordanpadams** [comment]
Copy that. Thanks @matthewtiscareno

**Comment by rgdeen** [comment]
Sorry I missed this discussion earlier.  Could not disagree more @matthewtiscareno .  Consider a tool like the Image Atlas, which is multimission.  You want to provide users a facility to search for Filter Name.  It does not matter that the filter names are different for each mission... you want a single search facet in a consistent place that can be used to search.  If you want a menu of choices for that search facet, it's easy enough to auto-populate the choices from the available data - we do that sort of thing all the time.

In short, it's not about cross-mission search - you're right in that filter names are not consistent enough for that.  It's about cross-mission search *facets* .... what are the sorts of things users want to search on.  Providing a Filter search is easy if it's a single keyword.  Doing what @jordanpadams described to look in 12 different keywords for every mission is not (nor is it sustainable or scalable).  The *concept* is the same across missions, and that's the critical aspect for building multimission UIs and search tools, even if the *values* are not.  The entire IM concept was built around this idea: shared concepts, specialized as needed for each mission.  That's why it has an object-oriented structure.  Talk to Steve Hughes about that sometime.

To be even shorter, multimission search is all about shared concepts, not shared values.

FYI @jordanpadams to answer your original question, for the VGR PDART we compromised and have several keywords that are *both* in the standard discipline dictionaries and in the VGR dictionary.  Although I consider that icky, at least we have the multimission search facets preserved in most cases.  I am disturbed that the official VGR migration will likely not have these.

**Comment by matthewtiscareno** [comment]
@rgdeen:  What's the use of a single cross-mission keyword called `Filter` if (for example) `Green` and `GRN` appear as different values? 

Please see [how OPUS solves this problem](https://opus.pds-rings.seti.org/#/qtype-wavelength=any&unit-wavelength=microns&qtype-waveno=any&unit-waveno=1_cm&qtype-wavenores=any&unit-wavenores=1_cm_pixel&qtype-waveres=any&unit-waveres=microns_pixel&cols=opusid,instrument,planet,target,time1,observationduration&widgets=wavelength,waveres,waveno,wavenores,specflag,instrument,observationtype&order=time1,opusid&view=search&browse=gallery&cart_browse=gallery&startobs=1&cart_startobs=1&detail=) by using wavelength-based attributes (which really do correspond across data sets) rather than filter names (which do not). 

Also, as [I said above](https://github.com/pds-data-dictionaries/ldd-vgr/pull/14#issuecomment-2040377365), a unified cross-mission attribute called `Filter` would either have no enumerated list (in which case you cannot guard against spelling errors) or would have a horrifyingly massive web of schematron rules.

**Pull request merged**
